import type {
  BusinessPost,
  BusinessProfile,
  BusinessReview,
  CollaborationIdea,
  Comment,
  ForumPost,
  UserProfile,
} from "./types";
import { DEMO_IMAGES } from "./demo-media";

export const SEED_USERS: UserProfile[] = [
  {
    id: "user-1",
    displayName: "Maria Chen",
    email: "maria@riverbendbakery.com",
    role: "business",
    planTier: "free",
    bio: "Owner of Riverbend Bakery — sourdough, pastries, and community events.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: [],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "user-2",
    displayName: "James Okonkwo",
    email: "james@greenlinelegal.com",
    role: "business",
    planTier: "free",
    bio: "Small-business attorney focused on contracts, leases, and compliance.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: [],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-01-12T14:00:00Z",
  },
  {
    id: "user-3",
    displayName: "Local Makers Co-op",
    email: "hello@localmakers.org",
    role: "organization",
    planTier: "free",
    bio: "Nonprofit supporting artisans and pop-up retail across Central Texas.",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: [],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "user-4",
    displayName: "Alex Rivera",
    email: "alex@example.com",
    role: "customer",
    planTier: "free",
    bio: "Freelance marketer helping local shops grow online and in the neighborhood.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    interestTags: ["marketing", "events"],
    industryInterests: ["Marketing & Print › Photography", "Entertainment & Events › Event Planning"],
    headline: "Open to local marketing and content projects",
    skills: ["Social media", "Content writing", "Email campaigns"],
    isSeekingWork: true,
    forumInterests: ["hiring", "local"],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "user-5",
    displayName: "Jordan Lee",
    email: "jordan@example.com",
    role: "customer",
    planTier: "free",
    bio: "Community member who loves supporting local restaurants and pop-ups.",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    interestTags: ["food", "local"],
    industryInterests: ["Food & Beverage › Restaurant", "Retail & Community › Maker & Craft"],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: [],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "user-6",
    displayName: "Sam Nguyen",
    email: "sam@example.com",
    role: "customer",
    planTier: "free",
    bio: "Product photographer and brand storyteller for local shops, restaurants, and makers.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    interestTags: ["photography", "branding"],
    industryInterests: ["Marketing & Print › Photography", "Entertainment & Events › Event Planning"],
    headline: "Available for local product & storefront shoots",
    skills: ["Product photography", "Lightroom", "Brand storytelling"],
    isSeekingWork: true,
    forumInterests: ["partnerships", "local"],
    feedScope: "state" as const,
    discoveryRadius: "state" as const,
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "user-7",
    displayName: "Priya Patel",
    email: "priya@example.com",
    role: "customer",
    planTier: "free",
    bio: "Event planner specializing in small-business launch parties and community pop-ups.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    interestTags: ["events", "hospitality"],
    industryInterests: ["Entertainment & Events","Food & Beverage"],
    headline: "Planning pop-ups and grand openings",
    skills: ["Event planning", "Vendor coordination", "Social promotion"],
    isSeekingWork: true,
    forumInterests: ["partnerships", "hiring"],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-04-12T14:00:00Z",
  },
  {
    id: "user-8",
    displayName: "Diego Morales",
    email: "diego@hillcountryfit.demo",
    role: "business",
    planTier: "pro",
    bio: "Founder of Hill Country Fitness — group classes and corporate wellness for local teams.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: ["local", "partnerships"],
    feedScope: "state" as const,
    discoveryRadius: "state" as const,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "user-9",
    displayName: "Elena Vasquez",
    email: "elena@cedarprint.demo",
    role: "business",
    planTier: "free",
    bio: "Owner of Cedar Park Print Co. — signage, menus, and marketing materials for local businesses.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    forumInterests: ["local"],
    feedScope: "city" as const,
    discoveryRadius: "city" as const,
    createdAt: "2026-03-01T11:00:00Z",
  },
];

export const SEED_BUSINESSES: BusinessProfile[] = [
  {
    id: "biz-1",
    ownerId: "user-1",
    name: "Riverbend Bakery",
    tagline: "Fresh bread, stronger neighborhoods",
    description:
      "Neighborhood bakery offering wholesale loaves to cafés and catering for local events. Looking to partner with coffee shops and farmers markets.",
    category: "Food & Beverage",
    subcategory: "Bakery & Pastry",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    website: "https://riverbendbakery.example",
    socialLinks: { instagram: "https://instagram.com/riverbendbakery" },
    phone: "(512) 555-0101",
    hours: "Tue–Sun 7am–3pm",
    importantInfo: "Wholesale orders need 48hr notice.",
    isHiring: true,
    services: [
      { name: "Wholesale loaves", description: "Sourdough and country loaves for cafés", actionType: "link", actionUrl: "https://riverbendbakery.example/order", actionLabel: "Request quote" },
      { name: "Event catering", description: "Pastry trays for offices and events", actionType: "form", actionLabel: "Place catering order" },
    ],
    mediaUrls: [DEMO_IMAGES.bakery, DEMO_IMAGES.bakery2],
    likeCount: 12,
    ratingAvg: 4.8,
    ratingCount: 6,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-2", "user-4", "user-5"],
    followingIds: ["biz-2"],
    createdAt: "2026-01-10T10:30:00Z",
  },
  {
    id: "biz-2",
    ownerId: "user-2",
    name: "Greenline Legal",
    tagline: "Practical legal guidance for growing businesses",
    description:
      "Flat-fee contract reviews, lease negotiations, and compliance checklists for startups and local shops.",
    category: "Professional Services",
    subcategory: "Legal",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    socialLinks: { linkedin: "https://linkedin.com/company/greenline-legal" },
    phone: "(512) 555-0202",
    hours: "Mon–Fri 9am–5pm",
    importantInfo: "Free 15-minute intro call for new clients.",
    isHiring: false,
    services: [
      { name: "Contract review", description: "Flat-fee vendor and client agreements" },
      { name: "Lease review", description: "Commercial lease negotiation support" },
    ],
    mediaUrls: [DEMO_IMAGES.legal],
    likeCount: 8,
    ratingAvg: 4.9,
    ratingCount: 4,
    intents: ["seeking_customers", "seeking_advice"],
    followerIds: ["user-1", "user-7"],
    followingIds: ["biz-1", "biz-3"],
    createdAt: "2026-01-12T14:30:00Z",
  },
  {
    id: "biz-3",
    ownerId: "user-3",
    name: "Local Makers Co-op",
    tagline: "Shared retail for independent creators",
    description:
      "Rotating storefront space, shared marketing, and vendor events. Always looking for new makers and community sponsors.",
    category: "Retail & Community",
    subcategory: "Maker & Craft",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    socialLinks: { facebook: "https://facebook.com/localmakerscoop" },
    phone: "(512) 555-0303",
    hours: "Wed–Sat 10am–6pm",
    importantInfo: "Vendor applications reviewed monthly.",
    isHiring: true,
    services: [
      { name: "Pop-up retail", description: "Short-term shelf space for makers" },
      { name: "Community events", description: "Markets and maker showcases" },
    ],
    mediaUrls: [DEMO_IMAGES.retail],
    likeCount: 5,
    ratingAvg: 4.6,
    ratingCount: 3,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-4", "user-6"],
    followingIds: ["biz-1"],
    createdAt: "2026-02-01T09:30:00Z",
  },
  {
    id: "biz-4",
    ownerId: "user-8",
    name: "Hill Country Fitness",
    tagline: "Stronger teams start local",
    description:
      "Boutique gym offering small-group training, corporate wellness packages, and pop-up classes at local businesses.",
    category: "Health & Wellness",
    subcategory: "Fitness & Gym",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    website: "https://hillcountryfit.demo",
    socialLinks: { instagram: "https://instagram.com/hillcountryfit" },
    phone: "(512) 555-0404",
    hours: "Mon–Sat 5am–9pm",
    importantInfo: "First class free for new members.",
    isHiring: true,
    services: [
      { name: "Corporate wellness", description: "On-site stretch and mobility sessions", price: "From $199/mo" },
      { name: "Small-group training", description: "6-person strength and conditioning", price: "$149/mo" },
    ],
    mediaUrls: [DEMO_IMAGES.fitness],
    likeCount: 15,
    ratingAvg: 4.7,
    ratingCount: 8,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-4", "user-9"],
    followingIds: ["biz-1"],
    createdAt: "2026-02-20T10:30:00Z",
  },
  {
    id: "biz-5",
    ownerId: "user-9",
    name: "Cedar Park Print Co.",
    tagline: "Print that pulls people in",
    description:
      "Fast turnaround on menus, yard signs, event banners, and branded merch for Austin-area small businesses.",
    category: "Marketing & Print",
    subcategory: "Print & Signage",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    socialLinks: {},
    phone: "(512) 555-0505",
    hours: "Mon–Fri 8am–6pm",
    importantInfo: "Rush jobs available with 24hr notice.",
    isHiring: false,
    services: [
      { name: "Menu & signage printing", description: "Restaurant and retail signage", price: "From $89" },
      { name: "Event banners", description: "Vinyl banners for markets and pop-ups", price: "From $120" },
      { name: "Brand merch", description: "T-shirts, tote bags, and stickers", price: "Custom quote" },
    ],
    mediaUrls: [DEMO_IMAGES.print, DEMO_IMAGES.coffee],
    likeCount: 9,
    ratingAvg: 4.9,
    ratingCount: 5,
    intents: ["seeking_customers", "open_to_partnerships"],
    followerIds: ["user-6", "user-1"],
    followingIds: ["biz-4"],
    createdAt: "2026-03-01T11:30:00Z",
  },
];

export const SEED_POSTS: ForumPost[] = [
  {
    id: "post-1",
    authorId: "user-2",
    authorName: "James Okonkwo",
    category: "legal_lessons",
    title: "Lesson learned: always get vendor agreements in writing",
    body: "We helped a café owner recover deposits after a pop-up vendor dispute. Key takeaway: even informal partnerships need a one-page agreement covering dates, fees, and cancellation.",
    commentIds: ["comment-1", "comment-2"],
    createdAt: "2026-03-05T16:00:00Z",
  },
  {
    id: "post-2",
    authorId: "user-1",
    authorName: "Maria Chen",
    category: "local",
    title: "Best farmers markets for new food vendors in Austin?",
    body: "We're expanding wholesale and considering weekend markets. Which local markets have been welcoming to bakeries? Any booth fee ranges?",
    commentIds: ["comment-3"],
    createdAt: "2026-03-08T11:00:00Z",
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    category: "partnerships",
    title: "Joint holiday pop-up — seeking food + gift vendors",
    body: "Planning a December shared storefront in Round Rock. Looking for 3–4 complementary businesses for a co-branded holiday market.",
    commentIds: [],
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorName: "Alex Rivera",
    category: "hiring",
    title: "Looking for part-time social help for a food truck",
    body: "A client of mine is launching a weekend food truck and needs someone local for Instagram stories and weekend posting. Paid gig, flexible hours.",
    commentIds: ["comment-4"],
    createdAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "post-5",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    category: "partnerships",
    title: "Free mini-shoots for 3 local shops this month",
    body: "Building my portfolio of Central Texas storefronts. Offering a free 1-hour product shoot to three bakeries or cafés in exchange for a testimonial.",
    commentIds: [],
    createdAt: "2026-05-08T12:00:00Z",
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "comment-1",
    postId: "post-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "This would have saved us a headache last year. Do you have a template you'd recommend for pop-ups?",
    createdAt: "2026-03-05T17:00:00Z",
  },
  {
    id: "comment-2",
    postId: "post-1",
    authorId: "user-2",
    authorName: "James Okonkwo",
    body: "Happy to share our one-page pop-up checklist in the forum resources section soon.",
    createdAt: "2026-03-05T18:30:00Z",
  },
  {
    id: "comment-3",
    postId: "post-2",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    body: "Sunset Valley market has been great for us — friendly to first-time vendors.",
    createdAt: "2026-03-08T14:00:00Z",
  },
  {
    id: "comment-4",
    postId: "post-4",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "We work with a few food vendors — happy to intro you if helpful.",
    createdAt: "2026-05-01T14:30:00Z",
  },
];

export const SEED_COLLABORATIONS: CollaborationIdea[] = [
  {
    id: "collab-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    businessId: "biz-1",
    title: "Bakery + coffee shop co-branded breakfast box",
    summary:
      "Partner with a local roaster to sell weekend breakfast boxes: pastry, loaf, and beans.",
    lookingFor: "Coffee shop or roaster within 10 miles of Austin",
    location: "Austin, TX",
    status: "open",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "collab-2",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    businessId: "biz-3",
    title: "Shared loyalty program for indie retailers",
    summary:
      "Pilot a punch-card style rewards program across 5–8 small shops in Williamson County.",
    lookingFor: "Retail owners interested in cross-promotion",
    location: "Round Rock / Georgetown, TX",
    status: "in_discussion",
    createdAt: "2026-03-06T15:00:00Z",
  },
  {
    id: "collab-3",
    authorId: "user-8",
    authorName: "Diego Morales",
    businessId: "biz-4",
    title: "Office wellness + bakery breakfast pop-up",
    summary: "Partner with a bakery for post-class recovery snacks and co-branded morning events.",
    lookingFor: "Food business near Cedar Park / Leander",
    location: "Cedar Park, TX",
    status: "open",
    createdAt: "2026-04-18T09:00:00Z",
  },
];

export const SEED_BUSINESS_POSTS: BusinessPost[] = [
  {
    id: "bpost-1",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "update",
    title: "New weekend sourdough drop — Saturdays at 8am",
    body: "Starting this Saturday we're doing a limited sourdough drop at the shop. Follow us for weekly flavors and wholesale availability for cafés.",
    mediaUrls: [DEMO_IMAGES.bakery],
    engagementScore: 42,
    isTrending: true,
    commentCount: 2,
    likeCount: 5,
    createdAt: "2026-05-10T08:00:00Z",
  },
  {
    id: "bpost-2",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "job",
    title: "Now hiring a part-time pastry assistant",
    body: "Looking for someone with early-morning availability Tue–Sat. Great entry point if you want to learn artisan baking in a neighborhood shop.",
    mediaUrls: [],
    engagementScore: 28,
    isTrending: false,
    commentCount: 1,
    likeCount: 3,
    createdAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "bpost-3",
    businessId: "biz-3",
    businessName: "Local Makers Co-op",
    businessCategory: "Retail & Community",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    postType: "update",
    title: "June maker market — vendor spots open",
    body: "Ten spots left for our June community market. Food vendors welcome. Apply through our profile or message us for the vendor packet.",
    mediaUrls: [DEMO_IMAGES.retail],
    engagementScore: 35,
    isTrending: true,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-12T10:00:00Z",
  },
  {
    id: "bpost-4",
    businessId: "biz-4",
    businessName: "Hill Country Fitness",
    businessCategory: "Health & Wellness",
    authorId: "user-8",
    authorName: "Diego Morales",
    postType: "deal",
    title: "Free corporate stretch sessions this month",
    body: "We're piloting 20-minute desk-break mobility sessions for local offices. First session free for teams of 8–20 people in Cedar Park.",
    mediaUrls: [DEMO_IMAGES.fitness],
    engagementScore: 19,
    isTrending: false,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-14T07:30:00Z",
  },
  {
    id: "bpost-5",
    businessId: "biz-5",
    businessName: "Cedar Park Print Co.",
    businessCategory: "Marketing & Print",
    authorId: "user-9",
    authorName: "Elena Vasquez",
    postType: "deal",
    title: "Grand opening banner bundle — 15% off in May",
    body: "New shop opening? We bundled yard signs, window clings, and Instagram-ready photo backdrops for local launches. Mention BizList for 15% off.",
    mediaUrls: [DEMO_IMAGES.print],
    engagementScore: 24,
    isTrending: false,
    commentCount: 1,
    likeCount: 3,
    createdAt: "2026-05-15T11:00:00Z",
  },
  {
    id: "bpost-6",
    businessId: "biz-2",
    businessName: "Greenline Legal",
    businessCategory: "Professional Services",
    authorId: "user-2",
    authorName: "James Okonkwo",
    postType: "deal",
    title: "Summer lease review special for retail pop-ups",
    body: "Pop-up and short-term retail leases need different terms than standard commercial leases. Flat-fee review available through June.",
    mediaUrls: [DEMO_IMAGES.legal],
    engagementScore: 15,
    isTrending: false,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-08T15:00:00Z",
  },
];

export const SEED_BUSINESS_REVIEWS: BusinessReview[] = [
  {
    id: "review-1",
    businessId: "biz-1",
    authorId: "user-4",
    authorName: "Alex Rivera",
    rating: 5,
    body: "Best sourdough in the neighborhood. Maria catered pastries for our shop launch and everyone asked where they came from.",
    createdAt: "2026-04-20T12:00:00Z",
  },
  {
    id: "review-2",
    businessId: "biz-1",
    authorId: "user-5",
    authorName: "Jordan Lee",
    rating: 5,
    body: "Friendly team, consistent quality, and they remember regulars. The Saturday drop is worth the early trip.",
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "review-3",
    businessId: "biz-2",
    authorId: "user-7",
    authorName: "Priya Patel",
    rating: 5,
    body: "James reviewed our pop-up vendor agreement in plain English. Saved us from a bad cancellation clause.",
    createdAt: "2026-04-25T16:00:00Z",
  },
  {
    id: "review-4",
    businessId: "biz-3",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    rating: 4,
    body: "Great community energy and foot traffic during market days. Vendor onboarding was straightforward.",
    createdAt: "2026-05-01T13:00:00Z",
  },
  {
    id: "review-5",
    businessId: "biz-5",
    authorId: "user-1",
    authorName: "Maria Chen",
    rating: 5,
    body: "Elena turned around new menu boards in 48 hours before our seasonal launch. Quality and communication were excellent.",
    createdAt: "2026-05-06T10:00:00Z",
  },
];

export function getBusinessById(id: string): BusinessProfile | undefined {
  return SEED_BUSINESSES.find((b) => b.id === id);
}

export function getPostById(id: string): ForumPost | undefined {
  return SEED_POSTS.find((p) => p.id === id);
}

export function getCommentsForPost(postId: string): Comment[] {
  return SEED_COMMENTS.filter((c) => c.postId === postId);
}

export function getUserById(id: string): UserProfile | undefined {
  return SEED_USERS.find((u) => u.id === id);
}

export function getBusinessPostsForBusiness(businessId: string): BusinessPost[] {
  return SEED_BUSINESS_POSTS.filter((p) => p.businessId === businessId);
}

export function getBusinessReviewsForBusiness(businessId: string): BusinessReview[] {
  return SEED_BUSINESS_REVIEWS.filter((r) => r.businessId === businessId);
}
