import type {
  BusinessEvent,
  BusinessPost,
  BusinessPostComment,
  BusinessProfile,
  BusinessReview,
  CollaborationComment,
  CollaborationIdea,
  Comment,
  EventComment,
  ForumPost,
  UserProfile,
} from "./types";
import { DEMO_IMAGES } from "./demo-media";

export const SEED_USERS: UserProfile[] = [
  {
    id: "user-1",
    displayName: "Maria Chen",
    email: "maria@riverbendbakery.com",
    role: "business",
    planTier: "free",
    bio: "Owner of Riverbend Bakery — sourdough, pastries, and community events.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    country: "US",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: [],
    discoveryRadius: "city" as const,
    createdAt: "2026-01-10T10:00:00Z",
    avatarUrl: DEMO_IMAGES.avatarMaria,
  },
  {
    id: "user-2",
    displayName: "James Okonkwo",
    email: "james@greenlinelegal.com",
    role: "business",
    planTier: "free",
    bio: "Small-business attorney focused on contracts, leases, and compliance.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    country: "US",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: [],
    discoveryRadius: "city" as const,
    createdAt: "2026-01-12T14:00:00Z",
  },
  {
    id: "user-3",
    displayName: "Local Makers Co-op",
    email: "hello@localmakers.org",
    role: "organization",
    planTier: "free",
    bio: "Nonprofit supporting artisans and pop-up retail across Central Texas.",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    country: "US",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: [],
    discoveryRadius: "city" as const,
    createdAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "user-4",
    displayName: "Alex Rivera",
    email: "alex@example.com",
    role: "customer",
    planTier: "free",
    bio: "Freelance marketer helping local shops grow online and in the neighborhood.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    country: "US",
    interestTags: ["marketing", "events"],
    industryInterests: ["Marketing & Print › Photography", "Entertainment & Events › Event Planning"],
    headline: "Open to local marketing and content projects",
    skills: ["Social media", "Content writing", "Email campaigns"],
    isSeekingWork: true,
    experienceText: "3 years helping Austin cafés and shops with social content and email campaigns.",
    resumeText: "Alex Rivera — freelance marketer in Austin, TX.\nSkills: Social media, Content writing, Email campaigns.",
    targetJobTitles: ["Social Media Coordinator", "Marketing Assistant"],
    jobAlertOptIn: true,
    followDigestFrequency: "weekly",
    forumInterests: ["hiring", "local"],
    discoveryRadius: "city" as const,
    createdAt: "2026-03-15T11:00:00Z",
    avatarUrl: DEMO_IMAGES.avatarAlex,
  },
  {
    id: "user-5",
    displayName: "Jordan Lee",
    email: "jordan@example.com",
    role: "customer",
    planTier: "free",
    bio: "Community member who loves supporting local restaurants and pop-ups.",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    country: "US",
    interestTags: ["food", "local"],
    industryInterests: ["Food & Beverage › Restaurant", "Retail & Community › Maker & Craft"],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: [],
    discoveryRadius: "city" as const,
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "user-6",
    displayName: "Sam Nguyen",
    email: "sam@example.com",
    role: "customer",
    planTier: "free",
    bio: "Product photographer and brand storyteller for local shops, restaurants, and makers.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    country: "US",
    interestTags: ["photography", "branding"],
    industryInterests: ["Marketing & Print › Photography", "Entertainment & Events › Event Planning"],
    headline: "Available for local product & storefront shoots",
    skills: ["Product photography", "Lightroom", "Brand storytelling"],
    isSeekingWork: true,
    experienceText: "5 years shooting product and storefront photography for local brands.",
    resumeText: "Sam Nguyen — product photographer in Austin, TX.\nSkills: Product photography, Lightroom, Brand storytelling.",
    targetJobTitles: ["Photographer", "Graphic Designer"],
    jobAlertOptIn: true,
    followDigestFrequency: "weekly",
    forumInterests: ["partnerships", "local"],
    discoveryRadius: "state" as const,
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "user-7",
    displayName: "Priya Patel",
    email: "priya@example.com",
    role: "customer",
    planTier: "free",
    bio: "Event planner specializing in small-business launch parties and community pop-ups.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    country: "US",
    interestTags: ["events", "hospitality"],
    industryInterests: ["Entertainment & Events","Food & Beverage"],
    headline: "Planning pop-ups and grand openings",
    skills: ["Event planning", "Vendor coordination", "Social promotion"],
    isSeekingWork: true,
    experienceText: "Organized 20+ pop-up markets and shop launch events across Williamson County.",
    resumeText: "Priya Patel — event planner in Cedar Park, TX.\nSkills: Event planning, Vendor coordination, Social promotion.",
    targetJobTitles: ["Event Planning", "Marketing Assistant"],
    jobAlertOptIn: true,
    followDigestFrequency: "monthly",
    forumInterests: ["partnerships", "hiring"],
    discoveryRadius: "city" as const,
    createdAt: "2026-04-12T14:00:00Z",
  },
  {
    id: "user-8",
    displayName: "Diego Morales",
    email: "diego@hillcountryfit.demo",
    role: "business",
    planTier: "pro",
    bio: "Founder of Hill Country Fitness — group classes and corporate wellness for local teams.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    country: "US",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: ["local", "partnerships"],
    discoveryRadius: "state" as const,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "user-9",
    displayName: "Elena Vasquez",
    email: "elena@cedarprint.demo",
    role: "business",
    planTier: "free",
    bio: "Owner of Cedar Park Print Co. — signage, menus, and marketing materials for local businesses.",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    country: "US",
    interestTags: [],
    industryInterests: [],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "none",
    forumInterests: ["local"],
    discoveryRadius: "city" as const,
    createdAt: "2026-03-01T11:00:00Z",
  },
  {
    id: "user-blake",
    displayName: "Blake",
    email: "blake.vieyra@gmail.com",
    role: "customer",
    planTier: "free",
    bio: "Local community member exploring neighborhood businesses.",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    country: "US",
    interestTags: ["local", "food"],
    industryInterests: ["Food & Beverage › Bakery"],
    headline: "",
    skills: [],
    isSeekingWork: false,
    experienceText: "",
    resumeText: "",
    targetJobTitles: [],
    jobAlertOptIn: false,
    followDigestFrequency: "weekly",
    forumInterests: ["local"],
    discoveryRadius: "city" as const,
    createdAt: "2026-05-01T12:00:00Z",
    avatarUrl: DEMO_IMAGES.avatarBlake,
  },
];

export const SEED_BUSINESSES: BusinessProfile[] = [
  {
    id: "biz-1",
    ownerId: "user-1",
    name: "Riverbend Bakery",
    tagline: "Fresh bread, stronger neighborhoods",
    description:
      "Neighborhood bakery offering wholesale loaves to cafés and catering for local events. Looking to partner with coffee shops and farmers markets.",
    category: "Food & Beverage",
    subcategory: "Bakery & Pastry",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78704",
    country: "US",
    website: "https://riverbendbakery.example",
    socialLinks: { instagram: "https://instagram.com/riverbendbakery" },
    phone: "(512) 555-0101",
    hours: "Tue–Sun 7am–3pm",
    importantInfo: "Wholesale orders need 48hr notice.",
    isHiring: true,
    jobTitle: "Baker",
    jobDescription: "Join our team baking fresh pastries and breads daily.",
    jobRequirements: "Early morning availability, food handler certification preferred.",
    jobApplicationForm: {
      questions: [
        {
          id: "short-fit",
          kind: "short",
          label: "Why do you want to work early mornings at a bakery?",
          required: true,
          placeholder: "Share relevant experience…",
        },
        {
          id: "short-availability",
          kind: "short",
          label: "Which days Tue–Sat can you work?",
          required: true,
          placeholder: "e.g. Tue, Thu, Sat",
        },
        {
          id: "important-food-handler",
          kind: "important",
          label: "Do you have a valid Texas food handler certificate?",
          required: true,
          placeholder: "Yes / No / In progress",
        },
        {
          id: "legal-work-auth",
          kind: "legal",
          label: "I am legally authorized to work in the United States.",
          required: true,
        },
        {
          id: "legal-scheduling",
          kind: "legal",
          label: "I understand scheduling may include early-morning shifts starting at 4am.",
          required: true,
        },
      ],
    },
    services: [
      {
        name: "Wholesale loaves",
        description: "Sourdough and country loaves for cafés, restaurants, and farmers markets. Baked fresh Tuesday through Sunday.",
        price: "From $6/loaf",
        quantity: "Min. 12 loaves per order · 48-hour notice required",
        imageUrl: DEMO_IMAGES.bakery,
        serviceType: "Food & drink",
        actionType: "form",
      },
      {
        name: "Event catering",
        description: "Custom pastry trays for corporate breakfasts, pop-ups, and private events. Seasonal flavors available.",
        price: "From $80/tray",
        quantity: "Trays feed 20–40 guests · book 72 hrs ahead",
        imageUrl: DEMO_IMAGES.bakery2,
        serviceType: "Service",
        actionType: "form",
      },
    ],
    mediaUrls: [DEMO_IMAGES.bakery, DEMO_IMAGES.bakery2],
    likeCount: 12,
    ratingAvg: 4.8,
    ratingCount: 6,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-2", "user-4", "user-5"],
    followingIds: ["biz-2"],
    createdAt: "2026-01-10T10:30:00Z",
  },
  {
    id: "biz-2",
    ownerId: "user-2",
    name: "Greenline Legal",
    tagline: "Practical legal guidance for growing businesses",
    description:
      "Flat-fee contract reviews, lease negotiations, and compliance checklists for startups and local shops.",
    category: "Professional Services",
    subcategory: "Legal",
    city: "Austin",
    state: "TX",
    county: "",
    zipCode: "78701",
    country: "US",
    socialLinks: { linkedin: "https://linkedin.com/company/greenline-legal" },
    phone: "(512) 555-0202",
    hours: "Mon–Fri 9am–5pm",
    importantInfo: "Free 15-minute intro call for new clients.",
    isHiring: false,
    jobTitle: "",
    jobDescription: "",
    jobRequirements: "",
    jobApplicationForm: { questions: [] },
    services: [
      { name: "Contract review", description: "Flat-fee review of vendor agreements, client contracts, and NDAs. Clear summary with redlines included.", price: "$299 flat fee", quantity: "Delivered in 3–5 business days · unlimited Q&A", imageUrl: DEMO_IMAGES.legal, serviceType: "Service", actionType: "form" },
      { name: "Lease review", description: "Commercial and pop-up lease analysis with negotiation support. We flag hidden clauses and propose counterterms.", price: "$399 flat fee", quantity: "Covers leases up to 20 pages · one revision round", imageUrl: DEMO_IMAGES.legal, serviceType: "Service", actionType: "form" },
    ],
    mediaUrls: [DEMO_IMAGES.legal],
    likeCount: 8,
    ratingAvg: 4.9,
    ratingCount: 4,
    intents: ["seeking_customers", "seeking_advice"],
    followerIds: ["user-1", "user-7"],
    followingIds: ["biz-1", "biz-3"],
    createdAt: "2026-01-12T14:30:00Z",
  },
  {
    id: "biz-3",
    ownerId: "user-3",
    name: "Local Makers Co-op",
    tagline: "Shared retail for independent creators",
    description:
      "Rotating storefront space, shared marketing, and vendor events. Always looking for new makers and community sponsors.",
    category: "Retail & Community",
    subcategory: "Maker & Craft",
    city: "Round Rock",
    state: "TX",
    county: "",
    zipCode: "78664",
    country: "US",
    socialLinks: { facebook: "https://facebook.com/localmakerscoop" },
    phone: "(512) 555-0303",
    hours: "Wed–Sat 10am–6pm",
    importantInfo: "Vendor applications reviewed monthly.",
    isHiring: true,
    jobTitle: "Retail Associate",
    jobDescription: "Help customers discover local artisan products and manage pop-up vendor relations.",
    jobRequirements: "Customer service experience, passion for local makers.",
    jobApplicationForm: { questions: [] },
    services: [
      { name: "Pop-up retail", description: "Short-term shared shelf space in our Round Rock storefront. Perfect for local makers testing a new product line.", price: "From $150/month", quantity: "2–4 ft of dedicated shelf · 30 and 90-day terms", imageUrl: DEMO_IMAGES.retail, serviceType: "Retail", actionType: "form" },
      { name: "Vendor market booth", description: "Reserve a 10×10 booth at our seasonal maker markets. Includes table, signage space, and co-op social promotion.", price: "$75 per market day", quantity: "One booth per vendor · setup 1 hr before open", imageUrl: DEMO_IMAGES.flyerMarket, serviceType: "Event / experience", actionType: "form" },
    ],
    mediaUrls: [DEMO_IMAGES.retail],
    likeCount: 5,
    ratingAvg: 4.6,
    ratingCount: 3,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-4", "user-6"],
    followingIds: ["biz-1"],
    createdAt: "2026-02-01T09:30:00Z",
  },
  {
    id: "biz-4",
    ownerId: "user-8",
    name: "Hill Country Fitness",
    tagline: "Stronger teams start local",
    description:
      "Boutique gym offering small-group training, corporate wellness packages, and pop-up classes at local businesses.",
    category: "Health & Wellness",
    subcategory: "Fitness & Gym",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    country: "US",
    website: "https://hillcountryfit.demo",
    socialLinks: { instagram: "https://instagram.com/hillcountryfit" },
    phone: "(512) 555-0404",
    hours: "Mon–Sat 5am–9pm",
    importantInfo: "First class free for new members.",
    isHiring: true,
    jobTitle: "Fitness Coach",
    jobDescription: "Lead group fitness classes and one-on-one personal training sessions.",
    jobRequirements: "Certified personal trainer (NASM, ACE, or equivalent), CPR certified.",
    jobApplicationForm: { questions: [] },
    services: [
      { name: "Corporate wellness", description: "20-minute on-site stretch and mobility sessions for office teams. Reduces injury and improves focus — no equipment needed.", price: "From $199/mo", quantity: "Teams of 8–30 people · 2 sessions/week included", imageUrl: DEMO_IMAGES.flyerFitness, serviceType: "Service", actionType: "form" },
      { name: "Small-group training", description: "Structured strength and conditioning in groups of 4–6. All fitness levels welcome — programming adjusts weekly.", price: "$149/mo", quantity: "4 sessions/week · max 6 per group", imageUrl: DEMO_IMAGES.fitness, serviceType: "Service", actionType: "form" },
    ],
    mediaUrls: [DEMO_IMAGES.fitness],
    likeCount: 15,
    ratingAvg: 4.7,
    ratingCount: 8,
    intents: ["seeking_customers", "open_to_partnerships", "hiring"],
    followerIds: ["user-4", "user-9"],
    followingIds: ["biz-1"],
    createdAt: "2026-02-20T10:30:00Z",
  },
  {
    id: "biz-5",
    ownerId: "user-9",
    name: "Cedar Park Print Co.",
    tagline: "Print that pulls people in",
    description:
      "Fast turnaround on menus, yard signs, event banners, and branded merch for Austin-area small businesses.",
    category: "Marketing & Print",
    subcategory: "Print & Signage",
    city: "Cedar Park",
    state: "TX",
    county: "",
    zipCode: "78613",
    country: "US",
    socialLinks: {},
    phone: "(512) 555-0505",
    hours: "Mon–Fri 8am–6pm",
    importantInfo: "Rush jobs available with 24hr notice.",
    isHiring: false,
    jobTitle: "",
    jobDescription: "",
    jobRequirements: "",
    jobApplicationForm: { questions: [] },
    services: [
      { name: "Menu & signage printing", description: "Laminated menus, chalkboard inserts, window clings, and A-frame signs. Rush turnaround available for grand openings.", price: "From $89", quantity: "Min. 10 pieces · same-day rush available", imageUrl: DEMO_IMAGES.print, serviceType: "Service", actionType: "form" },
      { name: "Event banners", description: "Weatherproof vinyl banners for outdoor markets, pop-ups, and storefronts. Grommets and hardware included.", price: "From $120", quantity: "Sizes up to 4×8 ft · 48-hr standard · 24-hr rush", imageUrl: DEMO_IMAGES.flyerPrint, serviceType: "Service", actionType: "form" },
    ],
    mediaUrls: [DEMO_IMAGES.print, DEMO_IMAGES.coffee],
    likeCount: 9,
    ratingAvg: 4.9,
    ratingCount: 5,
    intents: ["seeking_customers", "open_to_partnerships"],
    followerIds: ["user-6", "user-1"],
    followingIds: ["biz-4"],
    createdAt: "2026-03-01T11:30:00Z",
  },
];

export const SEED_POSTS: ForumPost[] = [
  {
    id: "post-1",
    authorId: "user-2",
    authorName: "James Okonkwo",
    category: "lessons_learned",
    title: "Lesson learned: always get vendor agreements in writing",
    body: "We helped a café owner recover deposits after a pop-up vendor dispute. Key takeaway: even informal partnerships need a one-page agreement covering dates, fees, and cancellation.",
    commentIds: ["comment-1", "comment-2"],
    createdAt: "2026-03-05T16:00:00Z",
  },
  {
    id: "post-2",
    authorId: "user-1",
    authorName: "Maria Chen",
    category: "local",
    title: "Best farmers markets for new food vendors in Austin?",
    body: "We're expanding wholesale and considering weekend markets. Which local markets have been welcoming to bakeries? Any booth fee ranges?",
    commentIds: ["comment-3"],
    createdAt: "2026-03-08T11:00:00Z",
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    category: "partnerships",
    title: "Joint holiday pop-up — seeking food + gift vendors",
    body: "Planning a December shared storefront in Round Rock. Looking for 3–4 complementary businesses for a co-branded holiday market.",
    commentIds: [],
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorName: "Alex Rivera",
    category: "hiring",
    title: "Looking for part-time social help for a food truck",
    body: "A client of mine is launching a weekend food truck and needs someone local for Instagram stories and weekend posting. Paid gig, flexible hours.",
    commentIds: ["comment-4"],
    createdAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "post-5",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    category: "partnerships",
    title: "Free mini-shoots for 3 local shops this month",
    body: "Building my portfolio of Central Texas storefronts. Offering a free 1-hour product shoot to three bakeries or cafés in exchange for a testimonial.",
    commentIds: [],
    createdAt: "2026-05-08T12:00:00Z",
  },
];

export const SEED_BUSINESS_EVENTS: BusinessEvent[] = [
  {
    id: "event-1",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessMediaUrl: DEMO_IMAGES.bakery,
    authorId: "user-1",
    title: "Weekend sourdough drop",
    description:
      "Limited sourdough loaves every Saturday at 8am. Flavors posted on our listing each Thursday.",
    location: "Riverbend Bakery",
    address: "1200 South Lamar Blvd",
    city: "Austin",
    state: "TX",
    county: "Travis",
    zipCode: "78704",
    country: "US",
    category: "Food & Beverage",
    imageUrl: DEMO_IMAGES.bakery2,
    startsAt: "2026-06-28T13:00:00Z",
    endsAt: "2026-06-28T16:00:00Z",
    capacity: 40,
    status: "published",
    goingCount: 24,
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "event-2",
    businessId: "biz-3",
    businessName: "Local Makers Co-op",
    businessMediaUrl: DEMO_IMAGES.retail,
    authorId: "user-3",
    title: "Summer maker meetup",
    description: "Meet local vendors, swap display tips, and preview new summer inventory.",
    location: "Local Makers Co-op",
    address: "200 Main St",
    city: "Round Rock",
    state: "TX",
    county: "Williamson",
    zipCode: "78664",
    country: "US",
    category: "Retail & Community",
    imageUrl: DEMO_IMAGES.retail,
    startsAt: "2026-07-05T18:00:00Z",
    capacity: 50,
    status: "published",
    goingCount: 12,
    createdAt: "2026-06-10T14:00:00Z",
  },
  {
    id: "event-3",
    businessId: "biz-4",
    businessName: "Hill Country Fitness",
    businessMediaUrl: DEMO_IMAGES.fitness,
    authorId: "user-8",
    title: "Sunrise park bootcamp",
    description: "Free community workout at Elizabeth Milburn Park. Bring water and a mat.",
    location: "Elizabeth Milburn Park",
    address: "1901 Sun Chase Blvd",
    city: "Cedar Park",
    state: "TX",
    county: "Williamson",
    zipCode: "78613",
    country: "US",
    category: "Health & Wellness",
    imageUrl: DEMO_IMAGES.fitness,
    startsAt: "2026-07-12T12:00:00Z",
    capacity: 40,
    status: "published",
    goingCount: 18,
    createdAt: "2026-06-15T09:00:00Z",
  },
];

export const SEED_EVENT_COMMENTS: EventComment[] = [
  {
    id: "event-comment-1",
    eventId: "event-1",
    authorId: "user-4",
    authorName: "Alex Rivera",
    body: "Will gluten-free loaves be available this week?",
    createdAt: "2026-06-20T15:30:00Z",
  },
  {
    id: "event-comment-2",
    eventId: "event-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "Yes — we usually have one GF option on Saturday drops. Follow the listing Thursday for the flavor list.",
    createdAt: "2026-06-20T16:05:00Z",
  },
  {
    id: "event-comment-3",
    eventId: "event-2",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    body: "Can vendors bring sample products to swap?",
    createdAt: "2026-06-18T11:00:00Z",
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "comment-1",
    postId: "post-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "This would have saved us a headache last year. Do you have a template you'd recommend for pop-ups?",
    createdAt: "2026-03-05T17:00:00Z",
  },
  {
    id: "comment-2",
    postId: "post-1",
    authorId: "user-2",
    authorName: "James Okonkwo",
    body: "Happy to share our one-page pop-up checklist in the forum resources section soon.",
    createdAt: "2026-03-05T18:30:00Z",
  },
  {
    id: "comment-3",
    postId: "post-2",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    body: "Sunset Valley market has been great for us — friendly to first-time vendors.",
    createdAt: "2026-03-08T14:00:00Z",
  },
  {
    id: "comment-4",
    postId: "post-4",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "We work with a few food vendors — happy to intro you if helpful.",
    createdAt: "2026-05-01T14:30:00Z",
  },
];

export const SEED_COLLABORATIONS: CollaborationIdea[] = [
  {
    id: "collab-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    businessId: "biz-1",
    title: "Bakery + coffee shop co-branded breakfast box",
    summary:
      "Partner with a local roaster to sell weekend breakfast boxes: pastry, loaf, and beans.",
    lookingFor: "Coffee shop or roaster within 10 miles of Austin",
    location: "Austin, TX",
    collaborationType: "proposal",
    status: "open",
    createdAt: "2026-03-01T10:00:00Z",
    interestedCount: 4,
    attachmentUrls: [],
  },
  {
    id: "collab-2",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    businessId: "biz-3",
    title: "Shared loyalty program for indie retailers",
    summary:
      "Pilot a punch-card style rewards program across 5–8 small shops in Williamson County.",
    lookingFor: "Retail owners interested in cross-promotion",
    location: "Round Rock / Georgetown, TX",
    collaborationType: "b2b_sale",
    status: "in_discussion",
    createdAt: "2026-03-06T15:00:00Z",
    interestedCount: 7,
    attachmentUrls: [],
  },
  {
    id: "collab-3",
    authorId: "user-8",
    authorName: "Diego Morales",
    businessId: "biz-4",
    title: "Office wellness + bakery breakfast pop-up",
    summary: "Partner with a bakery for post-class recovery snacks and co-branded morning events.",
    lookingFor: "Food business near Cedar Park / Leander",
    location: "Cedar Park, TX",
    collaborationType: "contract",
    status: "open",
    createdAt: "2026-04-18T09:00:00Z",
    interestedCount: 2,
    attachmentUrls: [],
  },
];

export const SEED_COLLABORATION_COMMENTS: CollaborationComment[] = [
  {
    id: "cc-1",
    collaborationId: "collab-1",
    authorId: "user-4",
    authorName: "Alex Rivera",
    body: "We roast in South Austin — interested in testing a weekend box.",
    attachmentUrls: [],
    createdAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "cc-2",
    collaborationId: "collab-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "Great — let's compare margins and pickup logistics.",
    attachmentUrls: [],
    createdAt: "2026-03-02T14:30:00Z",
  },
];

export const SEED_BUSINESS_POST_COMMENTS: Array<
  BusinessPostComment & { postId: string; authorId: string }
> = [
  {
    id: "bpc-1",
    postId: "bpost-1",
    authorId: "user-4",
    authorName: "Alex Rivera",
    body: "Can't wait — will you post flavors here each week?",
    createdAt: "2026-06-20T09:00:00Z",
  },
  {
    id: "bpc-2",
    postId: "bpost-1",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "Yes! We post the lineup every Thursday here and on our listing.",
    createdAt: "2026-06-20T10:15:00Z",
    parentId: "bpc-1",
  },
  {
    id: "bpc-7",
    postId: "bpost-1",
    authorId: "user-blake",
    authorName: "Blake",
    body: "i dont liek this business",
    createdAt: "2026-06-22T18:30:00Z",
    parentId: "bpc-1",
  },
  {
    id: "bpc-3",
    postId: "bpost-5",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    body: "Perfect timing — we need banners for a June pop-up.",
    createdAt: "2026-06-21T11:00:00Z",
  },
  {
    id: "bpc-4",
    postId: "bpost-5",
    authorId: "user-9",
    authorName: "Elena Vasquez",
    body: "Sam — message us your dimensions and we'll get you a quote today.",
    createdAt: "2026-06-21T11:45:00Z",
    parentId: "bpc-3",
  },
  {
    id: "bpc-5",
    postId: "bpost-8",
    authorId: "user-5",
    authorName: "Jordan Lee",
    body: "Could our PTA pick up on Wednesdays after school?",
    createdAt: "2026-06-21T14:00:00Z",
  },
  {
    id: "bpc-6",
    postId: "bpost-8",
    authorId: "user-1",
    authorName: "Maria Chen",
    body: "Absolutely — message us through the listing and we'll save a box for you.",
    createdAt: "2026-06-21T15:30:00Z",
    parentId: "bpc-5",
  },
];

const SEED_COMMENT_LIKE_COUNTS: Record<string, number> = {
  "bpc-1": 2,
  "bpc-2": 1,
};

export const SEED_BUSINESS_POSTS: BusinessPost[] = [
  {
    id: "bpost-1",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "update",
    title: "New weekend sourdough drop — Saturdays at 8am",
    body: "Starting this Saturday we're doing a limited sourdough drop at the shop. Follow us for weekly flavors and wholesale availability for cafés.",
    mediaUrls: [DEMO_IMAGES.bakery],
    engagementScore: 42,
    isTrending: true,
    commentCount: 3,
    likeCount: 5,
    createdAt: "2026-05-10T08:00:00Z",
  },
  {
    id: "bpost-2",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "job",
    title: "Now hiring a part-time pastry assistant",
    body: "Looking for someone with early-morning availability Tue–Sat. Great entry point if you want to learn artisan baking in a neighborhood shop.",
    mediaUrls: [],
    engagementScore: 28,
    isTrending: false,
    commentCount: 1,
    likeCount: 3,
    createdAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "bpost-3",
    businessId: "biz-3",
    businessName: "Local Makers Co-op",
    businessCategory: "Retail & Community",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    postType: "update",
    title: "June maker market — vendor spots open",
    body: "Ten spots left for our June community market. Food vendors welcome. Apply through our profile or message us for the vendor packet.",
    mediaUrls: [DEMO_IMAGES.retail],
    engagementScore: 35,
    isTrending: true,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-12T10:00:00Z",
  },
  {
    id: "bpost-4",
    businessId: "biz-4",
    businessName: "Hill Country Fitness",
    businessCategory: "Health & Wellness",
    authorId: "user-8",
    authorName: "Diego Morales",
    postType: "deal",
    title: "Free corporate stretch sessions this month",
    body: "We're piloting 20-minute desk-break mobility sessions for local offices. First session free for teams of 8–20 people in Cedar Park.",
    mediaUrls: [DEMO_IMAGES.fitness],
    engagementScore: 19,
    isTrending: false,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-14T07:30:00Z",
  },
  {
    id: "bpost-5",
    businessId: "biz-5",
    businessName: "Cedar Park Print Co.",
    businessCategory: "Marketing & Print",
    authorId: "user-9",
    authorName: "Elena Vasquez",
    postType: "deal",
    title: "Grand opening banner bundle — 15% off in May",
    body: "New shop opening? We bundled yard signs, window clings, and Instagram-ready photo backdrops for local launches. Mention BizList for 15% off.",
    mediaUrls: [DEMO_IMAGES.print],
    engagementScore: 24,
    isTrending: false,
    commentCount: 1,
    likeCount: 3,
    createdAt: "2026-05-15T11:00:00Z",
  },
  {
    id: "bpost-6",
    businessId: "biz-2",
    businessName: "Greenline Legal",
    businessCategory: "Professional Services",
    authorId: "user-2",
    authorName: "James Okonkwo",
    postType: "deal",
    title: "Summer lease review special for retail pop-ups",
    body: "Pop-up and short-term retail leases need different terms than standard commercial leases. Flat-fee review available through June.",
    mediaUrls: [DEMO_IMAGES.legal],
    engagementScore: 15,
    isTrending: false,
    commentCount: 0,
    likeCount: 0,
    createdAt: "2026-05-08T15:00:00Z",
  },
  {
    id: "bpost-7",
    businessId: "biz-3",
    businessName: "Local Makers Co-op",
    businessCategory: "Retail & Community",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    postType: "help_needed",
    title: "Volunteers needed for Saturday market setup",
    body: "We need 4 volunteers this Saturday 7–9am to help with tables and signage. Coffee and vendor lunch provided.",
    mediaUrls: [DEMO_IMAGES.retail],
    engagementScore: 12,
    isTrending: false,
    commentCount: 1,
    likeCount: 2,
    createdAt: "2026-06-18T14:00:00Z",
  },
  {
    id: "bpost-8",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "free",
    title: "Free day-old pastries for community groups",
    body: "Unsold loaves and pastries available after 4pm Mon–Wed. First come, first served — message us if you're a school or nonprofit pickup.",
    mediaUrls: [DEMO_IMAGES.bakery],
    engagementScore: 31,
    isTrending: true,
    commentCount: 3,
    likeCount: 8,
    createdAt: "2026-06-20T16:00:00Z",
  },
  {
    id: "bpost-9",
    businessId: "biz-4",
    businessName: "Hill Country Fitness",
    businessCategory: "Health & Wellness",
    authorId: "user-8",
    authorName: "Diego Morales",
    postType: "deal",
    title: "Summer kick-off — 3 months for the price of 2",
    body: "Join before July 4th and lock in our best rate of the year. Includes unlimited group classes, open gym, and a free nutrition consult. Flyer below — share with a friend and you both save an extra 10%.",
    mediaUrls: [DEMO_IMAGES.flyerFitness],
    engagementScore: 38,
    isTrending: true,
    commentCount: 2,
    likeCount: 11,
    createdAt: "2026-06-22T08:00:00Z",
  },
  {
    id: "bpost-10",
    businessId: "biz-1",
    businessName: "Riverbend Bakery",
    businessCategory: "Food & Beverage",
    authorId: "user-1",
    authorName: "Maria Chen",
    postType: "video",
    title: "Behind the scenes — sourdough at 4am",
    body: "We filmed a morning bake so you can see what goes into each loaf. From starter feed to the first crack out of the oven — this is why Saturday drops sell out by 9am.",
    mediaUrls: [DEMO_IMAGES.ytBakeryTour],
    engagementScore: 55,
    isTrending: true,
    commentCount: 4,
    likeCount: 18,
    createdAt: "2026-06-21T06:30:00Z",
  },
  {
    id: "bpost-11",
    businessId: "biz-5",
    businessName: "Cedar Park Print Co.",
    businessCategory: "Marketing & Print",
    authorId: "user-9",
    authorName: "Elena Vasquez",
    postType: "update",
    title: "New large-format printer — faster turnaround on banners",
    body: "We just installed a 64-inch wide-format machine. Same-day banners up to 4×8 ft are now on offer for Cedar Park and Round Rock customers. Walk-ins welcome.",
    mediaUrls: [DEMO_IMAGES.flyerPrint, DEMO_IMAGES.ytPrintProcess],
    engagementScore: 29,
    isTrending: false,
    commentCount: 1,
    likeCount: 6,
    createdAt: "2026-06-23T11:00:00Z",
  },
  {
    id: "bpost-12",
    businessId: "biz-3",
    businessName: "Local Makers Co-op",
    businessCategory: "Retail & Community",
    authorId: "user-3",
    authorName: "Local Makers Co-op",
    postType: "deal",
    title: "Market day flyer — July 4th weekend pop-up",
    body: "Thirty vendors, live music, and food trucks this July 4th weekend at the Round Rock Commons. Free entry. Print this flyer for $1 off any vendor purchase.",
    mediaUrls: [DEMO_IMAGES.flyerMarket],
    engagementScore: 44,
    isTrending: true,
    commentCount: 3,
    likeCount: 15,
    createdAt: "2026-06-24T09:00:00Z",
  },
];

export const SEED_BUSINESS_REVIEWS: BusinessReview[] = [
  {
    id: "review-1",
    businessId: "biz-1",
    authorId: "user-4",
    authorName: "Alex Rivera",
    rating: 5,
    body: "Best sourdough in the neighborhood. Maria catered pastries for our shop launch and everyone asked where they came from.",
    createdAt: "2026-04-20T12:00:00Z",
  },
  {
    id: "review-2",
    businessId: "biz-1",
    authorId: "user-5",
    authorName: "Jordan Lee",
    rating: 5,
    body: "Friendly team, consistent quality, and they remember regulars. The Saturday drop is worth the early trip.",
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "review-3",
    businessId: "biz-2",
    authorId: "user-7",
    authorName: "Priya Patel",
    rating: 5,
    body: "James reviewed our pop-up vendor agreement in plain English. Saved us from a bad cancellation clause.",
    createdAt: "2026-04-25T16:00:00Z",
  },
  {
    id: "review-4",
    businessId: "biz-3",
    authorId: "user-6",
    authorName: "Sam Nguyen",
    rating: 4,
    body: "Great community energy and foot traffic during market days. Vendor onboarding was straightforward.",
    createdAt: "2026-05-01T13:00:00Z",
  },
  {
    id: "review-5",
    businessId: "biz-5",
    authorId: "user-1",
    authorName: "Maria Chen",
    rating: 5,
    body: "Elena turned around new menu boards in 48 hours before our seasonal launch. Quality and communication were excellent.",
    createdAt: "2026-05-06T10:00:00Z",
  },
];

export function getBusinessById(id: string): BusinessProfile | undefined {
  return SEED_BUSINESSES.find((b) => b.id === id);
}

export function getPostById(id: string): ForumPost | undefined {
  return SEED_POSTS.find((p) => p.id === id);
}

export function getCommentsForPost(postId: string): Comment[] {
  return SEED_COMMENTS.filter((c) => c.postId === postId);
}

export function getUserById(id: string): UserProfile | undefined {
  return SEED_USERS.find((u) => u.id === id);
}

export function getBusinessPostCommentsForPost(
  postId: string,
  ownerId: string,
): BusinessPostComment[] {
  return SEED_BUSINESS_POST_COMMENTS.filter((c) => c.postId === postId)
    .map(({ postId: _postId, authorId, parentId, attachmentUrl, ...comment }) => {
      const user = getUserById(authorId);
      return {
        ...comment,
        authorId,
        parentId: parentId ?? null,
        attachmentUrl: attachmentUrl ?? null,
        isOwnerReply: authorId === ownerId,
        authorAvatarUrl: user?.avatarUrl ?? null,
        memberSince: user?.createdAt,
        likeCount: SEED_COMMENT_LIKE_COUNTS[comment.id] ?? 0,
        likedByViewer: false,
      };
    })
    .sort(
      (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
    );
}

export function getBusinessPostsForBusiness(businessId: string): BusinessPost[] {
  const business = SEED_BUSINESSES.find((b) => b.id === businessId);
  return SEED_BUSINESS_POSTS.filter((p) => p.businessId === businessId).map((post) => ({
    ...post,
    recentComments: business
      ? getBusinessPostCommentsForPost(post.id, business.ownerId)
      : [],
    commentCount:
      SEED_BUSINESS_POST_COMMENTS.filter((c) => c.postId === post.id).length ||
      post.commentCount,
  }));
}

export function getBusinessReviewsForBusiness(businessId: string): BusinessReview[] {
  return SEED_BUSINESS_REVIEWS.filter((r) => r.businessId === businessId);
}
